Deluge : {
    shape: "sql_table"
    Line In L:Audio
    Line In R:Audio
    Output L:Audio
    Output R:Audio
    Mic In:Audio
    Headphones:Audio
    Gate Out 1:Gate
    Gate Out 2:Gate
    Gate Out 3:Gate
    Gate Out 4:Gate
    CV Out 1:CV
    CV Out 2:CV
    USB: MIDI
    MIDI In:MIDI
    MIDI Out:MIDI
}
Strike Multipad:{
    shape: "sql_table"
    Main Out R:Audio
    Main Out L:Audio
    Aux Out R:Audio
    Aux Out L:Audio 
    Trigger In 1:Velocity / Switch
    Trigger In 2:Trigger / Head+Rim
    Trigger In 3:Trigger / Head+Rim
    Trigger In 4:Trigger / Head+Rim
    Trigger In 5:Trigger / Head+Rim
    Trigger In HH:Switch / Variable
    Foot Control 1:Switch / Variable
    Foot Control 2:Switch / Variable
    Foot Control 3:Switch / Variable
    Foot Control 4:Switch / Variable
    USB: MIDI / Audio
    MIDI In:MIDI
    MIDI Out/Thru:MIDI
}
Zoia
Syntakt
ES-9
2600
iPad
Mac
