2600: {
    label: Behringer ARP 2600
    Output: {
      label: Audio Output
      shape: "sql_table"
      L: TS
      R: TS
      Headphones: Stereo
    }
    MIDI: {
      shape: "sql_table"
      USB In: MIDI
      USB Out: MIDI
      DIN In: MIDI
      DIN Thru: MIDI
    }
    Control: {
      label: Control Port
      shape: "sql_table"
      Interval Latch: Switch
      Portamento: Switch
    }
    Panel In / Out: {
      label: Panel In / Out
      shape: "sql_table"
      CV: TS
      Gate: TS
      Trig: TS
      Audio: TS
    }
  }
  
  