Deluge: {
    label: "Synthstrom Audible Deluge"
    Input: {
      label: Audio Input
      shape: "sql_table"
      Line: TRS / L / R  / Stereo
      Mic: Built-in
    }
    Output: {
      label: Audio Output
      shape: "sql_table"
      L: TRS
      R: TRS
      Headphones: Stereo (1/8")
    }
    MIDI: {
      shape: "sql_table"
      USB In: MIDI
      USB Out: MIDI
      DIN In: MIDI
      DIN Out: MIDI
    }
    CV Output: {
      shape: "sql_table"
      Gate 1: 5-12V
      Gate 2: 5-12V
      Gate 3: 5-12V
      Gate 4: 5-12V
      CV 1: 0-10V
      CV 2: 0-10V
    }
  }
  