ES-9: {
    label: "Expert Sleepers ES-9"
    Input: {
      label: Audio Input
      shape: "sql_table"
      USB: 16 Channels
      SPDIF In: SPDIF
    }
    Output: {
        label: Audio Output
        shape: "sql_table"
        Main L: TRS
        Main R: TRS
        Headphones: Stereo
        USB: 16 Channels
        SPDIF Out: SPDIF
      }
      MIDI: {
      shape: "sql_table"
      USB In: MIDI
      USB Out: MIDI
    }
    Mixer Input: {
      label: Mixer Input (TS)
      shape: "sql_table"
      1: Audio / CV / Gate
      2: Audio / CV / Gate
      3: Audio / CV / Gate
      4: Audio / CV / Gate
      5: Audio / CV / Gate
      6: Audio / CV / Gate
      7: Audio / CV / Gate
      8: Audio / CV / Gate
      9: Audio / CV / Gate
      10: Audio / CV / Gate
      11: Audio / CV / Gate
      12: Audio / CV / Gate
      13: Audio / CV / Gate
      14: Audio / CV / Gate
    }
    Mixer Output: {
      label: Mixer Output (TS)
      shape: "sql_table"
      1: Audio / CV / Gate
      2: Audio / CV / Gate
      3: Audio / CV / Gate
      4: Audio / CV / Gate
      5: Audio / CV / Gate
      6: Audio / CV / Gate
      7: Audio / CV / Gate
      8: Audio / CV / Gate
    }
  }
  