direction: down

Deluge: {
  label: "Synthstrom Audible Deluge"
  Input: {
    label: Audio Input
    shape: "sql_table"
    Line: TRS / L / R  / Stereo
    Mic: Built-in
  }
  Output: {
    label: Audio Output
    shape: "sql_table"
    L: TRS
    R: TRS
    Headphones: Stereo (1/8")
  }
  MIDI: {
    shape: "sql_table"
    USB In: MIDI
    USB Out: MIDI
    DIN In: MIDI
    DIN Out: MIDI
  }
  CV Output: {
    shape: "sql_table"
    Gate 1: 5-12V
    Gate 2: 5-12V
    Gate 3: 5-12V
    Gate 4: 5-12V
    CV 1: 0-10V
    CV 2: 0-10V
  }
}

Multipad: {
  label: "Alesis Strike Multipad"
  Input: {
    label: Audio Input
    shape: "sql_table"
    Record L: TRS
    Record R: TRS
    USB L/R: USB Audio
  }
  Output: {
    label: Audio Output
    shape: "sql_table"
    Main R: TRS
    Main L: TRS
    Aux R: TRS
    Aux L: TRS
    Headphones: Stereo
    USB L/R: USB Audio
  }
  MIDI: {
    shape: "sql_table"
    USB In: MIDI
    USB Out: MIDI
    DIN In: MIDI
    DIN Out/Thru: MIDI
  }
  Trigger: {
    label: Trigger Input
    shape: "sql_table"
    1: Velocity / Switch
    2: Trigger / Head+Rim
    3: Trigger / Head+Rim
    4: Trigger / Head+Rim
    5: Trigger / Head+Rim
    HH: Switch / Variable
  }
  Foot: {
    label: Foot Control Input
    shape: "sql_table"
    1: Switch / Variable
    2: Switch / Variable
    3: Switch / Variable
    4: Switch / Variable
  }
}

Empress Zoia: {
  label: Empress Zoia
  Input: {
    label: Audio Input
    shape: "sql_table"
    L: TRS
    R: TRS
  }
  Output: {
    label: Audio Output
    shape: "sql_table"
    L: TRS
    R: TRS
  }
  MIDI: {
    shape: "sql_table"
    DIN In: MIDI
    DIN Out: MIDI
  }
  Control: {
    label: Control Port
    shape: "sql_table"
    MIDI In: Tip-Sleeve
    MIDI Out: Ring-Sleeve
    Expression: Tip-Sleeve
    CV In: Tip-Sleeve (0-5V)
    CV Out: Ring-Sleeve (0-5V)
    Switch: Tip-Sleeve
  }
}

Elektron Syntakt: {
  Input: {
    label: Audio Input
    shape: "sql_table"
    L: TRS
    R: TRS
    USB: USB Audio / Overbridge
  }
  Output: {
    label: Audio Output
    shape: "sql_table"
    L: TRS
    R: TRS
    USB: USB Audio / Overbridge
    Headphones: Stereo
  }
  MIDI: {
    shape: "sql_table"
    USB In: MIDI
    USB Out: MIDI
    DIN In: MIDI
    DIN Out: MIDI
  }
}

2600: {
  label: Behringer ARP 2600
  Output: {
    label: Audio Output
    shape: "sql_table"
    L: TS
    R: TS
    Headphones: Stereo
  }
  MIDI: {
    shape: "sql_table"
    USB In: MIDI
    USB Out: MIDI
    DIN In: MIDI
    DIN Thru: MIDI
  }
  Control: {
    label: Control Port
    shape: "sql_table"
    Interval Latch: Switch
    Portamento: Switch
  }
  Panel In / Out: {
    label: Panel In / Out
    shape: "sql_table"
    CV: TS
    Gate: TS
    Trig: TS
    Audio: TS
  }
}

iPad: {
  label: "Apple iPad Pro"
  Output: {
    label: Audio Output
    shape: "sql_table"
    Headphones: Stereo
  }
}

ES-9: {
  label: "Expert Sleepers ES-9"
  Output: {
    shape: "sql_table"
    Main L: TRS
    Main R: TRS
    Headphones: Stereo
    USB: 16 Channels
    SPDIF Out: SPDIF
  }
  Input: {
    shape: "sql_table"
    USB: 16 Channels
    SPDIF In: SPDIF
  }
  MIDI: {
    shape: "sql_table"
    USB In: MIDI
    USB Out: MIDI
  }
  Mixer Input: {
    label: Mixer Input (TS)
    shape: "sql_table"
    1: Audio / CV / Gate
    2: Audio / CV / Gate
    3: Audio / CV / Gate
    4: Audio / CV / Gate
    5: Audio / CV / Gate
    6: Audio / CV / Gate
    7: Audio / CV / Gate
    8: Audio / CV / Gate
    9: Audio / CV / Gate
    10: Audio / CV / Gate
    11: Audio / CV / Gate
    12: Audio / CV / Gate
    13: Audio / CV / Gate
    14: Audio / CV / Gate
  }
  Mixer Output: {
    label: Mixer Output (TS)
    shape: "sql_table"
    1: Audio / CV / Gate
    2: Audio / CV / Gate
    3: Audio / CV / Gate
    4: Audio / CV / Gate
    5: Audio / CV / Gate
    6: Audio / CV / Gate
    7: Audio / CV / Gate
    8: Audio / CV / Gate
  }
}

XR18: {
  label: "Behringer XR18"
  Input: {
    shape: "sql_table"
    1: TRS / XLR
    2: TRS / XLR
    3: TRS / XLR
    4: TRS / XLR
    5: TRS / XLR
    6: TRS / XLR
    7: TRS / XLR
    8: TRS / XLR
    9: TRS / XLR
    10: TRS / XLR
    11: TRS / XLR
    12: TRS / XLR
    13: TRS / XLR
    14: TRS / XLR
    15: TRS / XLR
    16: TRS / XLR
    17: TRS
    18: TRS
    USB: 18 Channels
  }
  Output: {
    shape: "sql_table"
    Aux 1: TRS / XLR
    Aux 2: TRS / XLR
    Aux 3: TRS / XLR
    Aux 4: TRS / XLR
    Aux 5: TRS / XLR
    Aux 6: TRS / XLR
    Main L: TRS / XLR
    Main R: TRS / XLR
    Headphones: Stereo
    USB: 18 Channels
  }
  MIDI: {
    shape: "sql_table"
    USB In: MIDI
    USB Out: MIDI
    DIN In: MIDI
    DIN Out: MIDI
  }
  Other: {
    shape: "sql_table"
    Ethernet: Remote
    WiFi: Remote
    USB: Remote
    Ultranet: Personal monitoring
  }
}
