build : 
	d2 studio.d2 studio.svg

run: 
	d2 --watch studio.d2 studio.svg

run-experimental: 
	# List of alternative elk algorithms
	# layered, force, sugiyama, radial, dagre, klay


	d2 --watch --layout elk --elk-algorithm radial  --sketch  studio.d2 studio.svg

init : 
	brew install d2