nts-2: {
  label: Korg NTS-2
  Input: {
    shape: "sql_table"
    1A: TS
    1B: RS
    2A: TS
    2B: RS
  }
  Thru: {
    shape: "sql_table"
    1A: TS
    1B: RS
    2A: TS
    2B: RS
  }
  Output: {
    shape: "sql_table"
    1: TS
    2: TS
  }
  Other: {
    shape: "sql_table"
    USB: Power / Firmare
  }
}
