##############
### Output ###
##############

### Synthstrom Audible Deluge ###
Deluge Output: {
  L
  R
}
Deluge Output.L -> Patch.Output.1
Deluge Output.R -> Patch.Output.2

### Alessis Strike Multipad ###
Multipad Output: {
  Main R
  Main L
}
Multipad Output.Main R -> Patch.Output.3
Multipad Output.Main L -> Patch.Output.4

### Empress Zoia ###
Zoia Output: {
  L
  R
}
Zoia Output.L -> Patch.Output.5
Zoia Output.R -> Patch.Output.6

### Elektron Syntakt ###
Syntakt Output: {
  L
  R
}
Syntakt Output.L -> Patch.Output.7
Syntakt Output.R -> Patch.Output.8

### Expert Sleepers ES-9 ###
ES-9 Output: {
  L
  R
}
ES-9 Output.L -> Patch.Output.9
ES-9 Output.R -> Patch.Output.10

### ARP 2600 ###
2600 Output: {
  L
  R
}
2600 Output.L -> Patch.Output.11
2600 Output.R -> Patch.Output.12

### DJI ###
DJI Output: {
  L
  R
}
DJI Output.L -> Patch.Output.13
DJI Output.R -> Patch.Output.14

### iPad ###
iPad Output: {
  L
  R
}
iPad Output.L -> Patch.Output.15
iPad Output.R -> Patch.Output.16

### XR18 ###
XR18 Output: {
  Aux 1
  Aux 2
  Aux 3
  Aux 4
  Aux 5
  Aux 6
  Main L
  Main R
}
XR18 Output.Aux 1 -> Patch.Output.17
XR18 Output.Aux 2 -> Patch.Output.18
XR18 Output.Aux 3 -> Patch.Output.19
XR18 Output.Aux 4 -> Patch.Output.20
XR18 Output.Aux 5 -> Patch.Output.21
XR18 Output.Aux 6 -> Patch.Output.22
XR18 Output.Main L -> Patch.Output.23
XR18 Output.Main R -> Patch.Output.24


################
### Patchbay ###
################

### Samson S-patch Plus ###
Patch: {
  label: Samson S-patch Plus
  Output: {
    1
    2
    3
    4
    5
    6
    7
    8
    9
    10
    11
    12
    13
    14
    15
    16
    17
    18
    19
    20
    21
    22
    23
    24
  }
  Input: {
    25
    26
    27
    28
    29
    30
    31
    32
    33
    34
    35
    36
    37
    38
    39
    40
    41
    42
    43
    44
    45
    46
    47
    48
  }
  Output.1 -> Input.25: Normal
  Output.2 -> Input.26: Normal
  Output.3 -> Input.27: Normal
  Output.4 -> Input.28: Normal
  Output.5 -> Input.29: Normal
  Output.6 -> Input.30: Normal 
  Output.7 -> Input.31: Normal
  Output.8 -> Input.32: Normal
  Output.9 -> Input.33: Normal
  Output.10 -> Input.34: Normal
  Output.11 -> Input.35: Normal
  Output.12 -> Input.36: Normal
  Output.13 -> Input.37: Normal
  Output.14 -> Input.38: Normal
  Output.15 -> Input.39: Normal
  Output.16 -> Input.40: Normal
  Output.17 -> Input.41: Normal
  Output.18 -> Input.42: Normal
  Output.19 -> Input.43: Normal
  Output.20 -> Input.44: Normal
  Output.21 -> Input.45: Normal
  Output.22 -> Input.46: Normal
  Output.23 -> Input.47: Normal
  Output.24 -> Input.48: Normal
}


#############
### Input ###
#############

### XR18 ###
XR18 Input: {
  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12
  13
  14
  15
  16
}
Patch.Input.25 -> XR18 Input.1
Patch.Input.26 -> XR18 Input.2
Patch.Input.27 -> XR18 Input.3
Patch.Input.28 -> XR18 Input.4
Patch.Input.29 -> XR18 Input.5
Patch.Input.30 -> XR18 Input.6
Patch.Input.31 -> XR18 Input.7
Patch.Input.32 -> XR18 Input.8
Patch.Input.33 -> XR18 Input.9
Patch.Input.34 -> XR18 Input.10
Patch.Input.35 -> XR18 Input.11
Patch.Input.36 -> XR18 Input.12
Patch.Input.37 -> XR18 Input.13
Patch.Input.38 -> XR18 Input.14
Patch.Input.39 -> XR18 Input.15
Patch.Input.40 -> XR18 Input.16

### Synthstrom Audible Deluge ###
Deluge Input: {
  Line L
  Line R
}
Patch.Input.41 -> Deluge Input.Line L
Patch.Input.42 -> Deluge Input.Line R

### Alessis Strike Multipad ###
Multipad Input: {
  Record L
  Record R
}
Patch.Input.43 -> Multipad Input.Record L
Patch.Input.44 -> Multipad Input.Record R

### Empress Zoia ###
Zoia Input: {
  L
  R
}
Patch.Input.45 -> Zoia Input.L
Patch.Input.46 -> Zoia Input.R

### Elektron Syntakt ###
Syntakt Input: {
  L
  R
}
Patch.Input.47 -> Syntakt Input.L
Patch.Input.48 -> Syntakt Input.R
