Synthstrom Audible Deluge : {
    shape: "sql_table"
    Line In L:Audio
    Line In R:Audio
    Output L:Audio
    Output R:Audio
    Mic In:Audio
    Headphones:Audio
    Gate Out 1:Gate
    Gate Out 2:Gate
    Gate Out 3:Gate
    Gate Out 4:Gate
    CV Out 1:CV
    CV Out 2:CV
    USB: MIDI
    MIDI In:MIDI
    MIDI Out:MIDI
}
Alesis Strike Multipad:{
    shape: "sql_table"
    Main Out R:Audio
    Main Out L:Audio
    Aux Out R:Audio
    Aux Out L:Audio 
    Trigger In 1:Velocity / Switch
    Trigger In 2:Trigger / Head+Rim
    Trigger In 3:Trigger / Head+Rim
    Trigger In 4:Trigger / Head+Rim
    Trigger In 5:Trigger / Head+Rim
    Trigger In HH:Switch / Variable
    Foot Control 1:Switch / Variable
    Foot Control 2:Switch / Variable
    Foot Control 3:Switch / Variable
    Foot Control 4:Switch / Variable
    USB: MIDI / Audio
    MIDI In:MIDI
    MIDI Out/Thru:MIDI
}
Empress Zoia {
    shape: "sql_table"
    Input L:Audio
    Input R:Audio
    Output L:Audio
    Output R:Audio
    MIDI In:MIDI
    MIDI Out:MIDI
    Control Port: MIDI / EXP / CV / Switch
    
}
Elektron Syntakt {
    shape: "sql_table"
    Input L:Audio
    Input R:Audio
    Output L:Audio
    Output R:Audio
    Headphones:Audio
    MIDI In:MIDI
    MIDI Out:MIDI
    MIDI Thru:MIDI
    USB: MIDI / Audio / Overbridge
}
Expert Sleepers ES-9 {
    shape: "sql_table"
    Main Out L:Audio
    Main Out R:Audio
    Headphones:Audio    
    SPDIF In:Audio
    SPDIF Out:Audio
    USB: MIDI / Audio
    Input 1:Audio / CV / Gate
    Input 2:Audio / CV / Gate
    Input 3:Audio / CV / Gate
    Input 4:Audio / CV / Gate
    Input 5:Audio / CV / Gate
    Input 6:Audio / CV / Gate
    Input 7:Audio / CV / Gate
    Input 8:Audio / CV / Gate
    Output 1:Audio / CV / Gate
    Output 2:Audio / CV / Gate
    Output 3:Audio / CV / Gate
    Output 4:Audio / CV / Gate
    Output 5:Audio / CV / Gate
    Output 6:Audio / CV / Gate
    Output 7:Audio / CV / Gate
    Output 8:Audio / CV / Gate
}
2600
iPad
Mac
