Elektron Syntakt: {
    Input: {
      label: Audio Input
      shape: "sql_table"
      L: TRS
      R: TRS
      USB: Stereo / Overbridge
    }
    Output: {
      label: Audio Output
      shape: "sql_table"
      L: TRS
      R: TRS
      USB: Stereo / Overbridge
      Headphones: Stereo
    }
    MIDI: {
      shape: "sql_table"
      USB In: MIDI
      USB Out: MIDI
      DIN In: MIDI
      DIN Out: MIDI
    }
  }
  
  