x-touch: {
    label: Behringer X-Touch
    MIDI: {
      shape: "sql_table"
      USB In:  MIDI / Mackie
      USB Out: MIDI
      DIN In: MIDI / Mackie
      DIN Out: MIDI
    }
    Foot Control: {
      shape: "sql_table"
      Footsw 1: Trigger
      Footsw 2: Trigger
      Expression Pedal: Expression
    }
    Other: {
      shape: "sql_table"
      USB: Hub / MIDI
      USB Hub 1: USB Client
      USB Hub 2: USB Client
      Remote: Ethernet
    }
  }
  