XR18: {
  label: "Behringer XR18"
  Input: {
    shape: "sql_table"
    1: TRS / XLR
    2: TRS / XLR
    3: TRS / XLR
    4: TRS / XLR
    5: TRS / XLR
    6: TRS / XLR
    7: TRS / XLR
    8: TRS / XLR
    9: TRS / XLR
    10: TRS / XLR
    11: TRS / XLR
    12: TRS / XLR
    13: TRS / XLR
    14: TRS / XLR
    15: TRS / XLR
    16: TRS / XLR
    17: TRS
    18: TRS
    USB: 18 Channels
  }
  Output: {
    shape: "sql_table"
    Aux 1: TRS / XLR
    Aux 2: TRS / XLR
    Aux 3: TRS / XLR
    Aux 4: TRS / XLR
    Aux 5: TRS / XLR
    Aux 6: TRS / XLR
    Main L: TRS / XLR
    Main R: TRS / XLR
    Headphones: Stereo
    USB: 18 Channels
  }
  MIDI: {
    shape: "sql_table"
    USB In: MIDI
    USB Out: MIDI
    DIN In: MIDI
    DIN Out: MIDI
  }
  Other: {
    shape: "sql_table"
    Ethernet: Remote
    WiFi: Remote
    USB: Remote
    Ultranet: Personal monitoring
  }
}
